
project_id = "gluggyghzalabvlvwqqk"

[functions.set-claims]
verify_jwt = true

[functions.get-user-data]
verify_jwt = true

[functions.get-mapbox-token]
verify_jwt = false

[functions.get-approved-jobs]
verify_jwt = false
