
# A string used to distinguish different Supabase projects on the same host. Defaults to the project ID.
project_id = "gluggyghzalabvlvwqqk"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

[functions]
[functions.check-team-membership]
verify_jwt = true
[functions.get-property-details]
verify_jwt = true
[functions.handle-project-update]
verify_jwt = true
[functions.add-team-member]
verify_jwt = true
[functions.check-existing-team-member]
verify_jwt = true
[functions.get-project-team-members]
verify_jwt = true
[functions.remove-team-member]
verify_jwt = true
[functions.get-user-data]
verify_jwt = true
[functions.get-approved-jobs]
verify_jwt = true
[functions.get-mapbox-token]
verify_jwt = true
[functions.set-claims]
verify_jwt = true
[functions.get-coach-projects]
verify_jwt = true
[functions.add-coaches-to-projects]
verify_jwt = true
[functions.scrape-property]
verify_jwt = true
