
project_id = "gluggyghzalabvlvwqqk"

[api]
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://localhost:5173"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"

[experimental]
trusted_cors_origins = ["localhost", "*.supabase.co", "*.supabase.in", "supabase.co", "supabase.in", "supabase.com"]

[[edge_functions]]
path = "add-coaches-to-projects"
verify_jwt = true
import_map = "supabase/functions/import_map.json"

[[edge_functions]]
path = "add-team-member"
verify_jwt = true
import_map = "supabase/functions/import_map.json"

[[edge_functions]]
path = "check-existing-team-member"
verify_jwt = true
import_map = "supabase/functions/import_map.json"

[[edge_functions]]
path = "check-team-membership"
verify_jwt = true
import_map = "supabase/functions/import_map.json"

[[edge_functions]]
path = "delete-account"
verify_jwt = true
import_map = "supabase/functions/import_map.json"

[[edge_functions]]
path = "get-approved-jobs"
verify_jwt = true
import_map = "supabase/functions/import_map.json"

[[edge_functions]]
path = "get-coach-projects"
verify_jwt = true
import_map = "supabase/functions/import_map.json"

[[edge_functions]]
path = "get-mapbox-geocoding"
verify_jwt = false
import_map = "supabase/functions/import_map.json"

[[edge_functions]]
path = "get-mapbox-token"
verify_jwt = true
import_map = "supabase/functions/import_map.json"

[[edge_functions]]
path = "get-project-team-members"
verify_jwt = true
import_map = "supabase/functions/import_map.json"

[[edge_functions]]
path = "get-property-details"
verify_jwt = true
import_map = "supabase/functions/import_map.json"

[[edge_functions]]
path = "get-user-data"
verify_jwt = true
import_map = "supabase/functions/import_map.json"

[[edge_functions]]
path = "handle-project-update"
verify_jwt = true
import_map = "supabase/functions/import_map.json"

[[edge_functions]]
path = "remove-team-member"
verify_jwt = true
import_map = "supabase/functions/import_map.json"

[[edge_functions]]
path = "scrape-property"
verify_jwt = true
import_map = "supabase/functions/import_map.json"

[[edge_functions]]
path = "scrape-zillow-images"
verify_jwt = true
import_map = "supabase/functions/import_map.json"

[[edge_functions]]
path = "send-meeting-confirmation"
verify_jwt = false
import_map = "supabase/functions/import_map.json"

[[edge_functions]]
path = "set-claims"
verify_jwt = true
import_map = "supabase/functions/import_map.json"

[[edge_functions]]
path = "notify-coaches-for-new-projects"
verify_jwt = true
import_map = "supabase/functions/import_map.json"
